#!/bin/bash

sudo -u postgres bash -c "psql -c \"DROP DATABASE folio_backend;\""
sudo -u postgres bash -c "psql -c \"DROP ROLE diku_mod_login;\""
sudo -u postgres bash -c "psql -c \"DROP ROLE diku_mod_permissions;\""
sudo -u postgres bash -c "psql -c \"DROP ROLE diku_mod_users;\""
sudo -u postgres bash -c "psql -c \"DROP ROLE diku_mod_inventory_storage;\""
sudo -u postgres bash -c "psql -c \"DROP ROLE diku_mod_configuration;\""
sudo -u postgres bash -c "psql -c \"DROP ROLE diku_mod_template_engine;\""
sudo -u postgres bash -c "psql -c \"DROP ROLE diku_mod_notify;\""
sudo -u postgres bash -c "psql -c \"DROP ROLE diku_mod_inventory_match;\""
sudo -u postgres bash -c "psql -c \"DROP ROLE diku_mod_sender;\""
sudo -u postgres bash -c "psql -c \"DROP ROLE diku_mod_email;\""
sudo -u postgres bash -c "psql -c \"DROP ROLE diku_mod_circulation_storage;\""
sudo -u postgres bash -c "psql -c \"DROP ROLE diku_mod_feesfines;\""
sudo -u postgres bash -c "psql -c \"DROP ROLE diku_mod_event_config;\""
sudo -u postgres bash -c "psql -c \"DROP ROLE diku_mod_password_validator;\""
sudo -u postgres bash -c "psql -c \"DROP ROLE diku_mod_source_record_storage;\""
sudo -u postgres bash -c "psql -c \"DROP ROLE diku_mod_calendar;\""
sudo -u postgres bash -c "psql -c \"DROP ROLE dbuser;\""
sudo -u postgres bash -c "psql -c \"CREATE USER dbuser WITH SUPERUSER PASSWORD 'qwerty';\""
sudo -u postgres bash -c "psql -c \"CREATE DATABASE folio_backend WITH OWNER=dbuser ENCODING 'UTF8' LC_CTYPE 'en_US.UTF-8' LC_COLLATE 'en_US.UTF-8' TEMPLATE 'template0';\""

